# Tensor Flow
A tensor is a vector generalized to higher dimensions. Each tensor represents a partialy defined computation that will eventually produce a value. Each tensor has a **data type** (ex: float32, int32, string etc) and a **shape** (that represents the dimension of data).

## Importing TF

In [26]:
import tensorflow as tf
session = tf.compat.v1.InteractiveSession()

C:\Users\pypas\anaconda3\envs\ML\lib\site-packages\tensorflow\python\client\session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


## Creating tensors

In [27]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(32, tf.int16)
floating = tf.Variable(3.4, tf.float64)

## Rank/Degree of Tensors
This means the number of dimensions involved in the tensor.
What we created above is a tensor of rank 0 (a **scalar**)

In [31]:
rank1_tensor = tf.Variable(["test", "test2", "test3"], tf.string)
rank2_tensor = tf.Variable([["test", "test2"], ["test3", "test4"]], tf.string)
tf.rank(rank2_tensor).eval()

2

## Shape of Tensors
How many items in each dimension

In [32]:
rank2_tensor.shape

TensorShape([Dimension(2), Dimension(2)])

## Changing shape

In [42]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1,[2,3,1])
tensor3 = tf.reshape(tensor2, [3,-1]) # -1 tells the tensor to calculte the size of the dimension in that place

print("Tensor 1 [1,2,3]")
print(tensor1.eval()) # [[[1,1,1], [1,1,1]]]
print("Tensor 2 [2,3,1]")
print(tensor2.eval()) # [[[1],[1],[1]], [[1],[1],[1]]]
print("Tensor 3 [3, -1]")
print(tensor3.eval()) # [[1,1], [1,1], [1,1]]

Tensor 1 [1,2,3]
[[[1. 1. 1.]
  [1. 1. 1.]]]
Tensor 2 [2,3,1]
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]
Tensor 3 [3, -1]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


## Types of Tensor
- Variable
- Constant
- Placeholder
- SparseTensor

With the exception of **Variable**, all of these tensors are immutable (their value may not change during execution)

In [43]:
session.close()